# Generated by Django 5.2.5 on 2025-08-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_remove_tablaposiciones_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='cancha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
