# Generated by Django 5.2.5 on 2025-08-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_partido_cancha_partido_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(choices=[('Junior A', 'Junior A'), ('Junior B', 'Junior B'), ('Senior', 'Senior')], default='Senior', max_length=20),
        ),
    ]
