# Generated by Django 5.2.5 on 2025-08-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaposiciones',
            name='puntos',
        ),
    ]
